### ISSUE TITLE
Failing Builds

### ISSUE THREAD

**Issue by tianon** [opencontainers/oci-conformance#106]
Recent PR merges are failing to build (and I did the merges, so I'm the lucky one getting the emails 🙃).

Someone™ should probably look into it and see what we can do to fix it.

https://github.com/opencontainers/oci-conformance/actions/runs/9701102281/job/26790176781

**Comment by sudo-bmitch** [comment]
Looks like the `| replace` statement in the template that was just merged is breaking the Liquid processor.

**Comment by vsoch** [comment]
If this is jekyll it should be something like:

`{{ $value.Meta.Name | downcase | replace: " ", "-" }}` 

Instead of  `{{ lower $value.Meta.Name | replace " " "-" }}` That's not tested, I just pulled that out of my head, but I'm pretty sure that jekyll doesn't have lower, and then replace requires a colon and common between parameters.

**Comment by vsoch** [comment]
But the reference to $value has me concerned it's some turducken combination of multiple things... :grimacing:

**Comment by jdolitsky** [comment]
The Github Pages I am pretty sure is now handled by Netlify instead and publishing successfully to https://conformance.opencontainers.org/

Pages is/was publishing to https://opencontainers.github.io/oci-conformance/ which seems broken. I just disabled github pages in the repo settings and I'll close this issue as done.
