### ISSUE TITLE
Scope of OCI Runtime Certification with software higher in the stack

### ISSUE THREAD

**Issue by alban** [opencontainers/oci-conformance#36]
The [OCI runtime validation suite](https://github.com/opencontainers/runtime-tools#testing-oci-runtimes) is able to test runtimes that expose the OCI Runtime interface to users (operations create, start, etc. and the config.json file). It should be possible to test software like [runc](https://github.com/opencontainers/runc), [bwrap-oci](https://github.com/projectatomic/bwrap-oci), [crun](https://github.com/giuseppe/crun), [railcar](https://github.com/oracle/railcar).

What about software that use a OCI runtime internally but don't directly expose the OCI Bundle to users, such as [containerd](https://github.com/containerd/containerd), [Docker](https://github.com/moby/moby), [CRI-O](https://github.com/kubernetes-incubator/cri-o/)? Should they be able to be certified in some ways?

I am not sure it would make much sense but I have not seen discussion whether it should be in scope of the certification or not.

Technically, if the software does not follow the [OCI Runtime Command Line Interface](https://github.com/opencontainers/runtime-tools/blob/master/docs/command-line-interface.md), the validation suite cannot test it. Exposing such a CLI interface in containerd or CRI-O does not make sense to me, since their goal is to expose a gRPC interface which is semantically different to the OCI Runtime CLI.

/cc @caniszczyk

**Comment by caniszczyk** [comment]
@alban I would like to see containerd, docker, cri-o to be certified, preferably via some testing method. Do you have any ideas how we can accomplish this or we do push the runtimes to expose this functionality?

Another option is to get a dump of their dependencies and ensure they use a unmodified release of runc (that they sign an agreement too) but that's not as useful as actually exercising the operations, similar to what we do with folks that use Kubernetes in products.

**Comment by caniszczyk** [comment]
Hey @opencontainers/tob, what's your thoughts here?

**Comment by taylorb-microsoft** [comment]
Interesting question... you could imagine a test version of runc that ensures that the interfaces are called in accordance with the spec and a test requirement that the runtime provide a log proving that they ran against that (in effect a unit test/mock runc).  The challenge I could see with that is obviously building/maintaining it.

**Comment by estesp** [comment]
All the "higher order" runtimes listed by @caniszczyk directly call `runc` (and in the case of Docker, do that through containerd), and expect (or deliver) a `runc` binary on the system.

*[I'm temporarily ignoring the extra fact that this `runc` binary is also pluggable with any "OCI compliant" runtime (I'm using the term compliant loosely given the repo we are in)].* 😇 

Other than validating that this installed `runc` meets the OCI spec, I'm not sure how else you would claim OCI compliance. Containerd can be called via API to be handed an OCI bundle (raw spec + mounted filesystem), such that you could almost do direct interactions with `runc`, but don't think that would be possible via Docker and I assume no via cri-o, based on the focus on being a CRI-compliant runtime.

Other than that rambling, I agree there is value with being able to claim higher order runtimes have "OCI compliance" as the expectation is that it, at some point, it will be a detriment to any container-executing product/project not being visibly seen as supporting OCI specs.

**Comment by wking** [comment]
On Wed, Apr 04, 2018 at 04:19:39PM +0000, Taylor Brown wrote:
> … you could imagine a test version of runc that ensures that the
> interfaces are called in accordance with the spec and a test
> requirement that the runtime provide a log proving that they ran
> against that (in effect a unit test/mock runc).

This is an interesting angle, effectively testing *caller* compliance
with the OCI Runtime Command Line Interface [1].  Note that CRI-O, at
least, would not currently pass such a test because it require
runc-specific extensions (kubernetes-incubator/cri-o#1260).  I assume
it would be up to the applicant to generate a test suite to drive
their engine through whatever subset of the CLI interface was required
for compliance.

A parallel approach more like an integration test would be driving
these higher-level engines through the existing runtime-tools
validation tests.  You could do that either by writing wrappers to
translate from the OCI Runtime Command Line Interface to the
higher-level APIs.  Or you could do it by specifying (and implementing
runtime-tools drivers for) additional testing APIs [2].

[1]: https://github.com/opencontainers/runtime-tools/blob/v0.5.0/docs/command-line-interface.md
[2]: https://github.com/opencontainers/runtime-tools/blob/v0.5.0/docs/runtime-compliance-testing.md#supported-apis

**Comment by alban** [comment]
> A parallel approach more like an integration test would be driving
these higher-level engines through the existing runtime-tools
validation tests.  You could do that either by writing wrappers to
translate from the OCI Runtime Command Line Interface to the
higher-level APIs.  Or you could do it by specifying (and implementing
runtime-tools drivers for) additional testing APIs [2].

[2]: https://github.com/opencontainers/runtime-tools/blob/v0.5.0/docs/runtime-compliance-testing.md#supported-apis

That seems difficult to me:
- the higher-level engine might utilize only a subset of OCI runtime features. For example, the CRI gRPC interface does not expose the feature to reuse an existing mount namespace from a specified path.
- the higher-level engine might use operations only together: [Create](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#create) and [Start](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#start). In that case, a test that only need to perform the "Create" operation might not have a translation in the higher-level engine API.

**Comment by wking** [comment]
> the higher-level engine might utilize only a subset of OCI runtime features.

The OCI Runtime Command Line Interface does not currently have anything I can point to that MUSTs support for all the specified commands.  That was my intention though, so I'll file a follow-up PR there and for this discussion let's assume it does.  I'm fine marking engines as compliant if they only need a subset of that API.  I'd like to mark engines as non-compliant if they need any extentions beyond that API.  That way, consumers would know they could use any runtime compliant with runtime-spec and the command line API with any higher-level engine compliant with the command line API.

> For example, the CRI gRPC interface does not expose the feature to reuse an existing mount namespace from a specified path.

That's fine, because mount namespaces are not part of the command line API, they're part of the runtime-spec.  For command line API compliance around container config JSON, you'd just have to verify that, if [`create`][1] had been called, that call was with a valid signature, that the caller gracefully handled both zero and non-zero exit codes, and that the caller didn't choke on [console socket][2] activity when it asked for `--console-socket`.

* a higher-level engine might use operations only together: Create and Start.

That's fine.

[1]: https://github.com/opencontainers/runtime-tools/blob/v0.5.0/docs/command-line-interface.md#create
[2]: https://github.com/opencontainers/runtime-tools/blob/v0.5.0/docs/command-line-interface.md#console-socket

**Comment by wking** [comment]
> The OCI Runtime Command Line Interface does not currently have anything I can point to that MUSTs support for all the specified commands. That was my intention though, so I'll file a follow-up PR there…

Filed as opencontainers/runtime-tools#615.

**Comment by alban** [comment]
> A parallel approach more like an integration test would be driving these higher-level engines through the existing runtime-tools validation tests.  You could do that either by writing wrappers to translate from the OCI Runtime Command Line Interface to the higher-level APIs.

I explored this approach both in containerd (https://github.com/opencontainers/runtime-tools/issues/653) and with the CRI interface (https://github.com/opencontainers/runtime-tools/issues/657) but I find this quite contrived and not so meaningful because the interfaces don't exactly match.

The other approaches mentioned in here:
- *caller* compliance: it would not test the same thing, so I'd not conflate it together with the same certification name as for runc.
 - dependencies dumping: although it is not a testing method, it is the simplest.

**Comment by caniszczyk** [comment]
Hey @vbatts and other @opencontainers/runc-maintainers, thoughts here

**Comment by crosbymichael** [comment]
Don't certify runc commits.  Who cares if vendors add commits or change things.  As long as X binary passes certification with Y criteria, who cares what code is used.  Same thing for certifying high level software.  First you should ask if they want to, next you should create a "test harness" for that software.  I think we are all learning that we cannot force ppl to use a CLI to be OCI compliant, people use JSON over http, GRPC, etc and probably already have full compliance today, the API just does not fit into our view of what a compliant runtime is right now.

**Comment by dongsupark** [comment]
Thanks for the reply.
Then I suppose the only valid option is 3.b), "Simply check for a semantic version of runc, and disallow 3rd-party patches".

**Comment by crosbymichael** [comment]
@dongsupark That is my opinion and others should weigh in, but I don't think, disallowing 3rd party patches is acceptable.  There are security fixes etc that distros will push.  We are certifying the API not the code.  If I have some patches in my personal runc for my own uses but it passes 100% of certification, how is it not valid?

**Comment by crosbymichael** [comment]
I think we said this multiple times, why not just make a test harness and let high level runtimes implement it, and that interface can be plugged into your test code?

**Comment by jdolitsky** [comment]
Going to close as outdated. Please re-open if more discussion necessary.
