### ISSUE TITLE
Membership Requirement for Certification?

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/oci-conformance#5]
There's some mixed views on whether an OCI membership should be required for certification or not. We should have a discussion to come up with a final decision here, there are pros and cons, but I generally like to require membership with certification as it's a membership benefit and helps sustain the project over the long term.

**Comment by RobDolinMS** [comment]
From the testing that @stephenrwalli and I did, it seems like runtime testing (when the applicant provides step-by-step instructions) is relatively lightweight.  

Toward that end, I'm inclined to suggest we make both the image certification / validation and runtime certification free and open to any product / organization.  

Thoughts from others? /cc @caniszczyk @jtborek @stephenrwalli

**Comment by caniszczyk** [comment]
@RobDolinMS 

Here's the the thing, the more I think about it, I want to require membership AT LEAST for the runtime specification because it helps fund the organization (protect the marks, staff etc) and don't want to be put in a situation where people certify and then don't renew their membership because they don't have a specific need. I want to make sure the OCI is sustainable in the long run and this is one way it helps.

**Comment by wking** [comment]
On Wed, Apr 26, 2017 at 02:30:31PM -0700, Chris Aniszczyk wrote:
> …I want to require membership AT LEAST for the runtime specification
> because it helps fund the organization (protect the marks, staff
> etc) and don't want to be put in a situation where people certify
> and then don't renew their membership because they don't have a
> specific need…

To paraphrase, it sounds like you're saying that the cost of the
certification program is mostly in maintaining the certifications, and
not in the initial generation.  So folks would be buying the initial
certification test (cheap), mark protection (expensive?), and …?

I don't see all that much need to link that to Membership (which in
the charter is more tied to the trademark board and votes for the
5-member TOB cohort [1]).  Since there is a benefit to having more
certified implementations (it makes it clear that there is less vendor
lock-in by adopting the OCI), it may make sense to decouple the
governance and certification fees.

[1]: https://www.opencontainers.org/about/governance §3.b, §4, and §6.g

**Comment by stephenrwalli** [comment]
I believe certification is a **product** thing. A **project** can claim to conform to the spec. It can run the suite that is available. It can post its results wherever it chooses so to do. All that is free. But a product wants to use the marks as a signal to the marketplace. I see no problem with making membership a condition of using the marks and posting results in the central location.

**Comment by jdolitsky** [comment]
Going to close as outdated. Please re-open if more discussion necessary.
